### ISSUE TITLE
Feature: Redeem stats

### ISSUE THREAD

**Issue by pebblepiglin** [RedBoardDev/plutusAnalytics#2]
I think now redeem feature is out, it'd be a nice stat to show like stackers currently.

Someone on the discord is reporting some of this data already, but I think it'd be nice getting granular data.

This is presumably by collecting PLU transaction amounts into the [0xe18f094ddd37f0eb2b651b65c4aad080afe90e51](https://etherscan.io/token/0xD8912C10681D8B21Fd3742244f44658dBA12264E?a=0xe18f094ddd37f0eb2b651b65c4aad080afe90e51) wallet.

The redeem PLU costs are predictable atm (need to also take into account the 50% off promotion, which doesn't have an end date announced), but will be reviewed at times to be fair based on PLU price.

**Comment by pebblepiglin** [comment]
I guess also one thing likely with redeem that will be more complex is that redeem promotions might only be offered based on some criteria. The current 50% off promotion was originally meant to be like that but instead is offered to all users.

**Comment by RedBoardDev** [comment]
For the moment, we'll show redeem value with bar and the sum with a line
![image](https://github.com/RedBoardDev/plutusAnalytics/assets/66514178/28b47f25-05a7-4cf5-b795-82d09e233758)
